import PptxGenJS from "pptxgenjs";

type Section = { title: string; content: string };

export async function downloadAsPpt(sections: Section[], topic: string) {
  const pptx = new PptxGenJS();
  pptx.title = topic;
  pptx.author = "AI Voice Teacher";
  pptx.layout = "LAYOUT_WIDE"; // 13.33 x 7.5

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { fill: "4338CA" };
  titleSlide.addText(topic, {
    x: 0.8,
    y: 2.0,
    w: 11.7,
    h: 2.0,
    fontSize: 36,
    fontFace: "Arial",
    color: "FFFFFF",
    bold: true,
    align: "center",
    valign: "middle",
  });
  titleSlide.addText("Generated by AI Voice Teacher", {
    x: 0.8,
    y: 4.2,
    w: 11.7,
    h: 0.8,
    fontSize: 16,
    fontFace: "Arial",
    color: "C7D2FE",
    align: "center",
  });

  // Content slides
  sections.forEach((section, i) => {
    const slide = pptx.addSlide();
    slide.background = { fill: "FFFFFF" };

    // Section number badge
    slide.addText(`${i + 1}`, {
      x: 0.5,
      y: 0.4,
      w: 0.6,
      h: 0.6,
      fontSize: 18,
      fontFace: "Arial",
      color: "FFFFFF",
      bold: true,
      align: "center",
      valign: "middle",
      fill: { color: "4338CA" },
      shape: pptx.shapes.OVAL,
    });

    // Title
    slide.addText(section.title, {
      x: 1.3,
      y: 0.4,
      w: 11.2,
      h: 0.7,
      fontSize: 28,
      fontFace: "Arial",
      color: "1E1B4B",
      bold: true,
      valign: "middle",
    });

    // Divider line
    slide.addShape(pptx.shapes.RECTANGLE, {
      x: 0.5,
      y: 1.3,
      w: 12.3,
      h: 0.04,
      fill: { color: "E0E7FF" },
    });

    // Content - split into bullet points by sentences
    const sentences = section.content
      .split(/(?<=[.!?])\s+/)
      .filter((s) => s.trim().length > 0);

    const bulletPoints = sentences.map((s) => ({
      text: s.trim(),
      options: {
        fontSize: 16,
        fontFace: "Arial" as const,
        color: "374151",
        bullet: { code: "2022" },
        lineSpacing: 28,
        paraSpaceBefore: 4,
      },
    }));

    slide.addText(bulletPoints, {
      x: 0.8,
      y: 1.6,
      w: 11.7,
      h: 5.4,
      valign: "top",
    });

    // Slide number
    slide.addText(`${i + 1} / ${sections.length}`, {
      x: 11.5,
      y: 7.0,
      w: 1.5,
      h: 0.4,
      fontSize: 11,
      fontFace: "Arial",
      color: "9CA3AF",
      align: "right",
    });
  });

  const safeName =
    topic.replace(/[^a-z0-9]+/gi, "_").replace(/^_|_$/g, "").substring(0, 60) ||
    "lecture";
  await pptx.writeFile({ fileName: `${safeName}.pptx` });
}
