project_id = "kmyennmabtncjkvheknn"

[functions.generate-lecture]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.chat-qa]
verify_jwt = false

[functions.extract-document-text]
verify_jwt = false
